// Generated by CoffeeScript 1.9.1
(function() {
  define(['aloha', 'jquery', 'overlay/overlay-plugin', 'ui/ui'], function(Aloha, jQuery, Popover, UI) {
    var DIALOG_HTML, editable, populator, selector, showModalDialog;
    editable = null;
    DIALOG_HTML = '<div class="plugin image modal fade" id="simModal" role="dialog">\n  <div class="modal-dialog">\n    <div class="modal-content">\n      <div class="modal-header">\n        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>\n        <h3>Simulations</h3>\n      </div>\n\n      <div class="modal-body">\n        <h4>Concord iframe URL</h4>\n        <div>\n          <select id="experiment-url">\n            <option value="http://connexions.github.io/simulations/energy-forms-and-changes/">Energy Forms &amp; Changes</option>\n            <option value="http://connexions.github.io/simulations/masses-and-springs/">Masses &amp; Springs</option>\n            <option value="http://connexions.github.io/simulations/moving-man/">Moving Man</option>\n            <option value="http://connexions.github.io/simulations/my-solar-system/">My Solar System</option>\n            <option value="http://connexions.github.io/simulations/states-of-matter/">States of Matter</option>\n            <option value="http://connexions.github.io/simulations/projectile-motion/">Projectile Motion</option>\n            <option value="http://connexions.github.io/simulations/vector-addition/">Vector Addition</option>\n            <option value="http://connexions.github.io/simulations/wave-interference/">Wave Interference</option>\n          </select>\n        </div>\n        <div>\n          <label>Width: </label>\n          <input name="width" type="number" placeholder="Width" required/>\n          <label>Height: </label>\n          <input name="height" type="number" placeholder="Height" required/>\n        </div>\n      </div>\n\n      <div class="modal-footer">\n        <a href="#" class="btn action insert">Insert</a>\n        <a href="#" class="btn" data-dismiss="modal">Cancel</a>\n      </div>\n    </div>\n  </div>\n</div>';
    showModalDialog = function($el) {
      var $height, $save, $url, $width, dialog;
      editable = Aloha.activeEditable.obj;
      dialog = jQuery(DIALOG_HTML);
      $save = dialog.find('.link-save');
      $url = dialog.find('#experiment-url');
      $width = dialog.find('*[name=width]');
      $height = dialog.find('*[name=height]');
      $url.val($el.attr('src'));
      $url.focus();
      $width.val($el.attr('width'));
      $height.val($el.attr('height'));
      $save.on('click', (function(_this) {
        return function(evt) {
          evt.preventDefault();
          return dialog.trigger('submit');
        };
      })(this));
      dialog.on('submit', (function(_this) {
        return function(evt) {
          evt.preventDefault();
          $el.attr('src', $url.val());
          return dialog.modal('hide');
        };
      })(this));
      dialog.modal('show');
      dialog.on('hidden', function() {
        return dialog.remove();
      });
      return dialog;
    };
    selector = 'iframe';
    populator = function($el) {
      var $bubble, change, remove;
      editable = Aloha.activeEditable;
      $bubble = jQuery('<div class="link-popover"></div>');
      change = jQuery('<button class="btn">Change...</div>').appendTo($bubble);
      change.on('click', (function(_this) {
        return function() {
          var dialog;
          Aloha.activeEditable = editable;
          return dialog = showModalDialog($el);
        };
      })(this));
      remove = jQuery('<button class="btn btn-danger">Remove</div>').appendTo($bubble);
      remove.on('click', (function(_this) {
        return function() {
          $el.remove();
          return jQuery(_this).popover('hide');
        };
      })(this));
      return $bubble.contents();
    };
    UI.adopt('insertSimulation', null, {
      click: function(e) {
        var dialog, newFrame;
        newFrame = jQuery('<iframe frameborder="1" height="960" width="580" scrolling="no"></iframe>');
        dialog = showModalDialog(newFrame);
        return dialog.find('.action.insert').on('click', (function(_this) {
          return function() {
            var range;
            Aloha.activateEditable(editable);
            newFrame.attr('src', dialog.find('#experiment-url').val());
            range = Aloha.Selection.getRangeObject();
            if (range.isCollapsed()) {
              GENTICS.Utils.Dom.extendToWord(range);
              GENTICS.Utils.Dom.insertIntoDOM(newFrame, range, Aloha.activeEditable.obj);
              range.startContainer = range.endContainer = newFrame.contents()[0];
              range.startOffset = 0;
              range.endOffset = newFrame.text().length;
              return dialog.modal('hide');
            } else {
              return GENTICS.Utils.Dom.addMarkup(range, newFrame, false);
            }
          };
        })(this));
      }
    });
    return Popover.register({
      hover: true,
      selector: selector,
      populator: populator
    });
  });

}).call(this);
