// Generated by CoffeeScript 1.8.0
(function() {
  define(['aloha', 'jquery', 'aloha/plugin', 'semanticblock/semanticblock-plugin', 'css!figure/css/figure-plugin.css'], function(Aloha, jQuery, Plugin, semanticBlock) {
    var activate, deactivate;
    activate = function(element) {
      var wrappingDiv;
      wrappingDiv = $(element).closest('.semantic-container');
      $(element).find('div.title').aloha();
      if ($(element).find('figcaption').children().length !== 1) {
        $(element).find('figcaption').wrapInner('<p>');
      }
      if (wrappingDiv.parent('p').length) {
        wrappingDiv.unwrap();
      }
      return $(element).find('figcaption > p').aloha();
    };
    deactivate = function(element) {
      $(element).find('div.title').mahalo();
      return $(element).find('figcaption > p').mahalo();
    };
    return Plugin.create('oer-figure', {
      getLabel: function() {
        return 'Figure';
      },
      activate: activate,
      deactivate: deactivate,
      selector: 'figure:not(figure figure)',
      placeholder: semanticBlock.placeholder,
      insertPlaceholder: function() {
        return semanticBlock.insertPlaceholder();
      },
      insertOverPlaceholder: function($content, $placeholder) {
        var $figure;
        $figure = $('<figure>').append($content);
        if (!$placeholder.parents('figure').length) {
          $figure.prepend('<div class="title">');
          $figure.append('<figcaption>');
          return semanticBlock.insertOverPlaceholder($figure, $placeholder);
        } else {
          return $placeholder.replaceWith($figure);
        }
      },
      init: function() {
        var plugin;
        plugin = this;
        return semanticBlock.register(plugin);
      }
    });
  });

}).call(this);
